### PR TITLE
SVG properties

### PR DESCRIPTION
**Pull request by Starzu**

### CODE REVIEW

**Comment by japgolly** [comment]
How is this meant to be used? These aren't for use in normal CSS right?

**Comment by Starzu** [comment]
I'm not an expert in CSS, but @malcheg sent me this example: https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Getting_started/SVG_and_CSS

It is standard CSS, but it contains some additional attributes for SVG.

**Comment by japgolly** [comment]
Ah thank you; makes sense. Ok 2 issues:

1. It's not obvious when using these (e.g. searching for desirable CSS attributes) that they are for SVG only. I think it would be better to prefix the names of each attribute with `svg`. So for example:
  ```scala
  final val clipRule = Attr.real("clip-rule")
  // ↑ would change to ↓
  final val svgClipRule = Attr.real("clip-rule")
  ```
  Do you agree that's a good idea? Do you have an objections against it?

2. Please update the changelog in [doc/history/0.4.md](https://github.com/japgolly/scalacss/blob/master/doc/history/0.4.md).

**Comment by Starzu** [comment]
I think it makes sense. I will push changes in a moment.

**Comment by japgolly** [comment]
:+1:

**Pull request merged**
