### PR TITLE
Scala 2.13 support

### PR DESCRIPTION
**Pull request by japgolly**

### CODE REVIEW

**Comment by japgolly** [comment]
Tests fail because String sorting order seems to be different on Scala 2.13.

**Comment by japgolly** [comment]
CSS is being produced in a different order in Scala 2.13 due to https://github.com/scala/bug/issues/11719

**Comment by FabioPinheiro** [comment]
About CSS is being produced in a different

1 Solution - We can use a SortedMap and Fix the test to be sorted by the key
2 Solution - We can try to make the test agnostic to the order of the output of the render.
Like try to convert the css output String to Json and compare the elements of the json

From what I understand from CSS the order of properties should not matter
The first solution will produce a more alphabetical order

What do you think?

**Comment by japgolly** [comment]
@FabioPinheiro Generally speaking, order does matter in CSS (see https://css-tricks.com/precedence-css-order-css-matters/). Given how scalacss works, off the top of my head I'm not sure there are cases where order matters, maybe unsafe children of multiple styles being applied to the same parent (which is already a practice scalacss recommends against).

I"ll figure something out. I want to get a release out today...

**Pull request merged**
