### PR TITLE
remove styleC fixes #48

### LINKED ISSUE #48: Abandon StyleC
It might be time to go back to the drawing board for `StyleC`. I barely use it and I was its biggest proponent. Does *anyone else* use it?

Similar to the Router situation in scalajs-react, it might be better to trade-in a little safety for a much larger portion of usability and Scala-friendliness. Would also allow us to drop the Shapeless dependency.

### PR DESCRIPTION
**Pull request by joprice**

### CODE REVIEW

**Comment by joprice** [comment]
Failed on travis with java 8 for some reason.

**Comment by japgolly** [comment]
Thanks for the @joprice. `StyleC` is on its way out but
1) I want to go back its motivating requirements and see if we can come up with an alternative before it's removed.
2) It might be better to deprecate it first before deleting it. (Although it is appealing to delete it fast because it takes Shapeless off the classpath.)

**Comment by joprice** [comment]
Ok no problem. Close this?

**Comment by japgolly** [comment]
Yeah, let's close it. Thank you for the PR though.

**Comment by japgolly** [comment]
@joprice Quasi-explanatory ramblings in #48. Let's just do it.

**Pull request merged**
